Vagrant.configure("2") do |config|

    config.vm.define "master" do |master|
      master.vm.box = "ubuntu/jammy64"
      master.vm.network "private_network", ip: "192.168.56.19"
      master.vm.network :forwarded_port, guest: 22, host: 1234
      master.vm.provider "virtualbox" do |vb|
        vb.memory = "2048"
        vb.cpus = "2"
      end
      master.vm.provision "shell", path: "docker-setup.sh"
    end

  

end
