
Vagrant.configure("2") do |config|
    config.vm.box = "ubuntu/jammy64"

    config.vm.network "private_network", ip: "192.168.56.21" 

    config.vm.provider "virtualbox" do |vb|
        vb.memory = "1024"  
        vb.cpus = 1         
    end

    config.vm.provision "shell", path: "setup-harbor.sh"
end